// Single place that reaches for Worker bindings. Loaders and actions import getDb()
// rather than touching `cloudflare:workers` directly, so the access pattern stays
// consistent as more routes land.

import { drizzle } from "drizzle-orm/d1";
import { env } from "cloudflare:workers";

// worker-configuration.d.ts is generated by `wrangler types` and picks up secrets from
// .dev.vars. Narrow it here so a missing regeneration cannot break the build.
interface Bindings {
  DB: D1Database;
  FILES?: R2Bucket;
  AI?: { run: (model: string, input: Record<string, unknown>) => Promise<unknown> };
  SESSION_SECRET?: string;
  BREVO_API_KEY?: string;
  ANTHROPIC_API_KEY?: string;
  AIRTABLE_API_KEY?: string;
  AIRTABLE_BASE_ID?: string;
  EMAIL_FROM?: string;
  EMAIL_FROM_NAME?: string;
  APP_BASE_URL?: string;
}

export const bindings = env as unknown as Bindings;

export function getDb() {
  return drizzle(bindings.DB);
}

/** The HMAC key every session cookie is signed and verified with.
 *
 *  There is deliberately no fallback. A published fallback key is a signing key an
 *  attacker already has: any deployment missing the binding would accept cookies
 *  minted for arbitrary user ids. Refusing to run is the safe failure. */
export function sessionSecret(): string {
  const secret = bindings.SESSION_SECRET;
  if (!secret) {
    throw new Error(
      "SESSION_SECRET is not set. Sessions cannot be signed without it. " +
        "Set it with `wrangler secret put SESSION_SECRET`, or in .dev.vars for local development."
    );
  }
  return secret;
}

export function appBaseUrl(): string {
  return bindings.APP_BASE_URL ?? "http://localhost:5173";
}
