// Single place that reaches for Worker bindings. Loaders and actions import getDb()
// rather than touching `cloudflare:workers` directly, so the access pattern stays
// consistent as more routes land.

import { drizzle } from "drizzle-orm/d1";
import { env } from "cloudflare:workers";

// worker-configuration.d.ts is generated by `wrangler types` and picks up secrets from
// .dev.vars. Narrow it here so a missing regeneration cannot break the build.
interface Bindings {
  DB: D1Database;
  FILES?: R2Bucket;
  AI?: { run: (model: string, input: Record<string, unknown>) => Promise<unknown> };
  SESSION_SECRET?: string;
  BREVO_API_KEY?: string;
  ANTHROPIC_API_KEY?: string;
  EMAIL_FROM?: string;
  EMAIL_FROM_NAME?: string;
  APP_BASE_URL?: string;
}

export const bindings = env as unknown as Bindings;

export function getDb() {
  return drizzle(bindings.DB);
}

export function sessionSecret(): string {
  const secret = bindings.SESSION_SECRET;
  if (!secret) {
    // Loud in production, tolerable locally: sessions still sign, but with a value
    // an attacker could guess. Set SESSION_SECRET in .dev.vars or via wrangler secret.
    console.warn("SESSION_SECRET is not set. Falling back to an insecure development value.");
    return "insecure-development-session-secret";
  }
  return secret;
}

export function appBaseUrl(): string {
  return bindings.APP_BASE_URL ?? "http://localhost:5173";
}
